<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="FirebaseAdmin" Version="3.5.0" />
		<PackageReference Include="FirebaseDatabase.net" Version="5.0.0" />
		<PackageReference Include="Google.Cloud.Firestore" Version="4.2.0" />
		<PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="9.0.0" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="9.0.0" />
		<PackageReference Include="Microsoft.Extensions.Http" Version="9.0.0" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Almoxarifado.Domain\Almoxarifado.Domain.csproj" />
	</ItemGroup>

</Project>